### ISSUE TITLE
Using with typescript – no type definitions for /backendless/es

### ISSUE THREAD

**Issue by stefanpl** [Backendless/JS-SDK#192]
I am trying to get going with the JavaScript SDK in a node.js environment.

I use typescript, which gets compiled by webpack, nothing too fancy. I am having a hard time getting any typings for the SDK though.

This will not trigger any complaints by the compiler, and I have types for the Backendless object.
BUT the `Backendless` object will actually be `undefined` at runtime.
```typescript
import Backendless from "backendless";
```

The following will trigger a TS warning (`Could not find a declaration file for module 'backendless/es'. '/node_modules/backendless/es/index.js' implicitly has an 'any' type.`), and I don't have any types on the imported object:
```typescript
import * as Backendless from "backendless/es";
```
But the import actually works, and I can use the api.

I am using this repo as a boilerplate: https://github.com/stefanpl/typescript-template
Only did `npm i backendless` and then tried to add some code to `entryPoint.ts`.

How can I have a functioning import with proper Typescript definitions?

**Comment by Valodya** [comment]
Hello @stefanpl 

Thank you for sharing this problem, the issue has been fixed in [the commit](https://github.com/Backendless/JS-SDK/commit/626b9a5bc293200cb7497a82fec0f65e758f6d0d)
Could you please upgrade the SDK to version 6.2.1 and check?

Regards, Vlad

**Comment by Valodya** [comment]
btw, you do not need to import it from `backendless/es` just use the following import

```
import Backendless from "backendless";
```

**Comment by stefanpl** [comment]
@Valodya @markpiller working now, thanks so much for the quick fix!
