### ISSUE TITLE
Realtime Database not working in bundled app

### ISSUE THREAD

**Issue by sauladam** [Backendless/JS-SDK#217]
I tried to replicate the example app for a movies list in Vite + Vue 

The expample code: https://backendless.com/real-time-database-quick-start-guide-for-javascript-developers/

Copy-pasting the example code and pulling Backendless directly into the HTML file is working as expected and all external updates are reflected in realtime. Nice! 🔥

Now I do the same with Vite + Vue, so i pull in Backendless via npm:

```bash
$ npm i backendless
```

And in my app:
```js
import Backendless from "backendless"
import { ref } from 'vue'

let APP_ID = "my-app-id"
let API_KEY = "my-app-key"

Backendless.initApp(APP_ID, API_KEY)

let moviesStore = Backendless.Data.of("Movies")
let moviesList = ref(null)

moviesStore.find(Backendless.DataQueryBuilder.create().setPageSize(100).setSortBy("created"))
    .then(result => {
      moviesList.value = result
      console.log(result)
      enableRealTime()
    })

let enableRealTime = () => {
  let rtHandlers = moviesStore.rt()

  rtHandlers.addUpdateListener(movie => {
    console.log("HANDLING UPDATE")
    moviesList.value = moviesList.value.map(m => m.objectId === movie.objectId ? movie : m)
  })
}
```
While the `find` part works fine, it's having trouble with the realtime handler. No errors are thrown, it is just not listening. It seems like it's not able to connect to the Websocket server.

Here's what the network tab looks like for the **single HTML file app**:
![Screenshot from 2021-08-17 08-40-30](https://user-images.githubusercontent.com/5918276/129676441-5e45aed3-de85-42d9-8eeb-0a05c4631c1d.png)

And that's it.

Meanwhile, in the **bundled app**, it looks like this:
![Screenshot from 2021-08-17 08-45-06](https://user-images.githubusercontent.com/5918276/129676863-69989cf0-fad9-445b-a336-de34a25fd862.png)

And it just keeps polling the /lookup endpoint forever without ever switching to a WS connection.

Both apps are using v6.2.22 of the Backendless JS SDK.

Am I missing something? 

Thanks a ton!

**Comment by Valodya** [comment]
Hello @sauladam 

Please move your issue to our [Support Forum](https://support.backendless.com/) in order to receive the answer/help asap.

This one I'm going to close.

Regards, Vlad

**Comment by sauladam** [comment]
Hey @Valodya

sorry, I wasn't aware of the support forum. Just jumped on the Backendless train yesterday while trying out Firebase alternatives and loving it so far!

Anyway, just moved the issue over to the forum. Thanks!
