### ISSUE TITLE
Add ability to pass options object to FB SDK login 

### ISSUE THREAD

**Issue by vengrov** [Backendless/JS-SDK#39]
Comes from [support](http://support.backendless.com/topic/client-sdk-login-with-facebook-permissions)

According to [Facebook SDK Doc](https://developers.facebook.com/docs/reference/javascript/FB.login/v2.7#permissions)

> By default, calling FB.login() will attempt to authenticate the user with only the basic permissions. If you want one or more additional permissions, call FB.login() with an option object, and set the scope parameter with a comma-separated list of the permissions you wish to request from the user.

Theoretically this should be enough to fix it

```
loginWithFacebookSdk: function(fieldsMapping, stayLoggedIn, async, options) {
    //...
            FB.login(function(response) {
                me._sendSocialLoginRequest(me, response, "facebook", fieldsMapping, stayLoggedIn, async);
            }, options);
    //...
},
```

**Comment by illyaV** [comment]
I've try to fix it, man
