### ISSUE TITLE
AngularJs 2 Version

### ISSUE THREAD

**Issue by Purus** [Backendless/JS-SDK#44]
Hi Team,

What's the AngularJs 2 version supported by the library? Currently we have AngularJs final available.

**Comment by Valodya** [comment]
Hi Purus

Backendless SDK does not depends on any libraries and frameworks.
You can use it with any framework you choose
As for Angular 2, if you write your code on TypeScript, your will need Backendless TypeScript definitions
You can find them here https://github.com/Backendless/JS-SDK/blob/master/libs/backendless.d.ts

Hope it helped you. Let us know if you have any problems or questions.
